server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/customer-service/**
              filters:
                - StripPrefix=1

            - id: cv-service
              uri: lb://cv-service
              predicates:
                - Path=/cv-service/**
              filters:
                - StripPrefix=1

            - id: reference-service
              uri: lb://reference-service
              predicates:
                - Path=/reference-service/**
              filters:
                - StripPrefix=1

            - id: mission-service
              uri: lb://mission-service
              predicates:
                - Path=/mission-service/**
              filters:
                - StripPrefix=1

            - id: matching-service
              uri: lb://matching-service
              predicates:
                - Path=/matching-service/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health

