server:
  port: 2001

spring:
  application:
    name: cv-service

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: jdbc:postgresql://postgres-cv:5432/cvdb
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 60000  # 60 seconds
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000  # 5 minutes
      max-lifetime: 1800000  # 30 minutes

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

  mvc:
    log-request-details: true

  retry:
    max-attempts: 5
    delay: 2000

logging:
  level:
    org.springframework.web: DEBUG
    org.mapstruct: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health