server:
  port: 2000

spring:
  application:
    name: customer-service

  mvc:
    log-request-details: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "anasbenbrahim491@gmail.com"
    password: "vkgw tqui loio ciro"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  retry:
    max-attempts: 5
    delay: 2000

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:customer-db

logging:
  level:
    org.springframework.web: DEBUG
    com.zaxxer.hikari: DEBUG  # Enable HikariCP logging for debugging

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health