server:
  port: 2000

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://postgres-customer:5432/customerdb
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 60000  # 60 seconds
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000  # 5 minutes
      max-lifetime: 1800000  # 30 minutes

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection_provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    hibernate:
      ddl-auto: update
    generate-ddl: true

  mvc:
    log-request-details: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "anasbenbrahim491@gmail.com"
    password: "vkgw tqui loio ciro"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  retry:
    max-attempts: 5
    delay: 2000

logging:
  level:
    org.springframework.web: DEBUG
    com.zaxxer.hikari: DEBUG  # Enable HikariCP logging for debugging

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health