server:
  port: 2002

spring:
  flyway:
    enabled: false
  application:
    name: reference-service

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:reference-db

  mvc:
    log-request-details: true
    static-path-pattern: /static/**

  retry:
    max-attempts: 5
    delay: 2000

logging:
  level:
    org.springframework.web: DEBUG
    org.mapstruct: DEBUG


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
