server:
  port: 2002

spring:
  flyway:
    enabled: false
  application:
    name: reference-service

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/cv-management-reference-service
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

  mvc:
    log-request-details: true
    static-path-pattern: /static/**

logging:
  level:
    org.springframework.web: DEBUG
    org.mapstruct: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


